apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "rafay-datadog.labels" . | nindent 4 }}
data:
  config.ini: |-
    [rafay]
    url = {{ .Values.config.url }}
    apikey = {{ .Values.config.apikey }}
    initialFilter = {{ .Values.config.filter }}
    interval = {{ .Values.config.interval }}
    
    [Datadog]
    host = {{ .Values.config.host }}
    apikey = {{ .Values.config.datadogkey }}
