apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    rafay.dev/registry-248j9vm: rafay-us-private
    rafay.dev/registry-ko7e3y2: rafay-us-private
    rafay.dev/registry-k6z33pm: rafay-us-private
  labels:
    app.kubernetes.io/name: nginx
spec:
  containers:
    - name: nginx
      image: registry.rafay.us/nginx-demo:latest
      imagePullPolicy: Always
      ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
      resources:
        limits:
          cpu: "500m"
          memory: "256Mi"
        requests:
          cpu: "250m"
          memory: "128Mi"
      securityContext:
        allowPrivilegeEscalation: false
        privileged: false
  terminationGracePeriodSeconds: 0