apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "rafay-splunk.labels" . | nindent 4 }}
data:
  config.ini: |-
    [rafay]
    url = {{ .Values.config.url }}
    apikey = {{ .Values.config.apikey }}
    initial_filter = 30d
    interval = 1m
    
    [Splunk]
    host = {{ .Values.config.host }}
    port = {{ .Values.config.port }}
    token = {{ .Values.config.token }}
    ssl_verify = {{ .Values.config.ssl_verify }}
    index = {{ .Values.config.index }}
